### ISSUE TITLE
Stoneguard maybe?

### ISSUE THREAD

**Issue by Pestfr0sch** [50k-Customs/DAF-XF#3]
Hey there Keda,

This question has probably been asked a million times, but how are the chances that a stoneguard will ever be added to your beautiful truck?

http://www.delrue.be/images/details/03372213.JPG

Greetings,
Pestfr0sch

**Comment by simon50keda** [comment]
Well there is almost none, because I don't like it. Moreover I already have long to do list for which I am not sure when it will be done ;)

Still I will leave this issue opened if some time in the future I decide to make it.

**Comment by Pestfr0sch** [comment]
I had in mind that at one point since the release of your DAF (yeah, I'm following this project since you first showed it in the scs forums) you mentioned that you didn't like stoneguards. But I thought maybe there will be a chance. Sometimes in the future. I probably will never stop hoping :D
