### ISSUE TITLE
6x2 Rearlift Chassis

### ISSUE THREAD

**Issue by LoaderSaints** [50k-Customs/DAF-XF#4]
Any chance that you would add a 6x2 Rearlift chassis (steerable & liftable rear wheels) like in the image below for this truck (just the chassis type, no need for custom sideskirts or wheel arches)?
http://i.imgur.com/gJ609Pf.jpg

**Comment by simon50keda** [comment]
I know it's a long since you posted this issue. However are you still interested in this chassis type?

**Comment by LoaderSaints** [comment]
Well, I don't drive semi-trailer trucks that much anymore so I don't have the need for such chassis anymore but a rigid version of the same chassis would be of interest since you have a 4x2 rigid chassis already (in the works at least).

**Comment by simon50keda** [comment]
Yep 6x2 will come together with 4x2 ;) So I am closing this issue, thx.
