### ISSUE TITLE
Cabin Accessories DLC Compatibility

### ISSUE THREAD

**Issue by danielpie** [50k-Customs/DAF-XF#5]
There seems to be an issue with the cabin accessories with v1.23.x of the game. Example: I get the following error when putting one of the hanging plush dice into the cabin.
<ERROR> [fs] Failed to open file "/material/ropes/rope_black.dlc_toys.mat" in the read_only mode
<ERROR> [material] Can not open '/material/ropes/rope_black.dlc_toys.mat"
The ropes appear in red, the game cannot load the textures. Perhaps SCS changed some file names?

**Comment by simon50keda** [comment]
I will take a look into it. Thx for reporting ;)

**Comment by simon50keda** [comment]
Fixed: 2f69a1569bc79ad14db88366bc3fd4666508978b

PS: Go to latest release and download compatibility new package from it: https://github.com/50k-Customs/DAF-XF/releases/latest
